# To read this file, run:
#    perldoc CONTRIBUTING.pod

=head1 NAME

How to contribute to C<github-keygen>?

=head1 DESCRIPTION

Patches are welcome!

They must be built against the
C<L<master|https://github.com/dolmen/github-keygen/tree/master>> branch,
then submitted as pull requests at GitHub.

The documentation is written using the
L<POD|http://perldoc.perl.org/perlpod.html> format. Use the C<perldoc> tool
to render it in a terminal:

    perldoc CONTRIBUTING.pod

=head1 PATCHING, STEP BY STEP

=over 4

=item 1. Get the source

    git clone --origin upstream git://github.com/dolmen/github-keygen.git
    cd github-keygen
    git checkout master

=item 2. Install build dependencies

Not required for doc patches.

    curl -L https://cpanmin.us | perl - --installdeps --with-develop .

=item 3. Make your fix/feature

    git checkout -b <my-patch> master

    $EDITOR bin/github-keygen

    # Test...
    bin/github-keygen ...

    # Run the author testsuite
    prove -v xt

    git commit

=item 4. Setup a fork

=item 4.1. L<Fork the project on GitHub|https://github.com/dolmen/github-keygen/>

=item 4.2. Link your local repo to your fork (just once)

(You are using C<github-keygen> isn't it?)

    git remote add github <github-user>.github.com:<github-user>/github-keygen.git

=item 5. Submit your work

=item 5.1 Push!

    git push github <my-patch>

=item 5.2 Submit a pull request on GitHub

=item 6. Loop

Redo from step 3.

=back

=head1 FOR RELEASE MANAGER

=over 4

=item * Bump C<$VERSION>

    git checkout master
    # Bump version number
    $EDITOR bin/github-keygen
    # Update changelog
    $EDITOR README.pod
    git add bin/github-keygen README.pod
    git commit

=item * Release

    git checkout master
    ./release.pl
    git push origin master release
    git push origin --tags

=back

=cut
