=head1 NAME

github-keygen - bootstrap your Github SSH configuration

=head1 SYNOPSIS

    git clone https://github.com/dolmen/github-keygen.git
    cd github-keygen
    ./github-keygen <my-github-username>

=head1 DESCRIPTION

This script ease initial environment setup for secure Github exchanges, but it
does much more than that:

=over 4

=item *

Create a new SSH private key

=item *

Setup a very secure SSH configuration for Github, independent of your other SSH
settings:

=over 4

=item -

Enable only the authentication method used with Github (publickey)

=item -

Disable bad things that could come from the Github hosts ("Trust no-one")

=back

=item *

Create unique host aliases for github.com/gist.github.com that you'll be able
to use in Git URLs to connect to a particular account. This gives uses the
flexibility to use multiple Github accounts.

    <account>.github.com:<repo-owner>/<repo>.git
    github.com:<repo-owner>/<repo>.git

in addition to:

    git@github.com:<repo-owner>/<repo>.git

=back

This script will:

=over 4

=item *

Create a new SSH key dedicated only to your Github connections in
F<~/.ssh/id_I<E<lt>github-accountE<gt>>@github>

=item *

Create the SSH configuration optimized for Github and dedicated to Github
(do not impact your other SSH configurations) in F<~/.ssh/config> (unless the
file already exists)

=item *

Install the Github SSH host authentication fingerprints in
F<~/.ssh/github_known_hosts>

=back

=head1 INSTALL

Fetch the script from GitHub:

    git clone https://github.com/dolmen/github-keygen.git
    cd github-keygen

Optional (but recommended to better understand what is done): install the
L<Text::Diff> Perl module. Use the one packaged by your system distribution
if possible.

=over 4

=item * Debian/Ubuntu:

    sudo apt-get install libtext-diff-perl

=item * RedHat/Fedora:

    sudo yum install perl-Text-Diff

=item * OpenSuse:

    sudo zipper install perl-Text-Diff

=item * Mandriva/Mageia/...:

    sudo urpmi install perl-Text-Diff

=item * CPAN:

Install L<Text::Diff|https://metacpan.org/module/Text::Diff> with your favorite
CPAN client.

=back

=head1 UPGRADE

To upgrade your config to the latest one, update C<github-keygen> and relaunch
it. It will update your F<~/.ssh/config> and show you the diff of what it
changed (if you have the L<Text::Diff> perl module).

    cd github-keygen
    git pull --rebase
    ./github-keygen

=head1 AUTHOR

Olivier MenguE<eacute>, L<mailto:dolmen@cpan.org>.

=head1 COPYRIGHT & LICENSE

Copyright E<copy> 2011 Olivier MenguE<eacute>.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see L<http://www.gnu.org/licenses/>.

=cut
