name: Test
on: [push]

jobs:
  test:
    name: Test
    if: github.ref != 'refs/heads/release'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out
      uses: actions/checkout@v6

    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: "5.40"
        # Install dependencies from cpanfile
        install-modules-with: cpanm
        install-modules-args: --with-develop

    - name: perl -c
      run: perl -c bin/github-keygen
    - name: Simulate release
      run: ./release.pl -n

  test-release:
    name: Test Release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/release'
    steps:
    - name: Check out
      uses: actions/checkout@v6
    - name: perl -c
      run: perl -c ./github-keygen

  test-ssh:
    name: Test SSH
    if: github.ref != 'refs/heads/release'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - run: ssh -V
    - name: Show GitHub public keys
      run: |
        ssh-keyscan -t ed25519 github.com gist.github.com 2>/dev/null
        ssh-keyscan -t ed25519 -p 443 ssh.github.com 2>/dev/null
    - name: Show GitHub kex algorithms
      run: ssh -vvv github.com 2>&1 | grep -A1 'server KEXINIT'
